### ISSUE TITLE
Positionsänderung von Elementen nach dem Speichern

### ISSUE THREAD

**Issue by jkoelm** [iqb-berlin/teststudio-lite-frontend#11]
Nach dem Speichern verschieben sich die einzelnen Elemente einer Aufgabe, wenn man sie vorher pixelgenau ausgerichtet hat, insbesondere bei Radio Buttons in Tabellen. Momentan kann das umgangen werden, indem man nach der Formatierung jeder Reihe die Aufgabe speichert und auf Voransicht klickt (.

**Comment by paflov** [comment]
Issue moved to [iqb-berlin/verona-player-dan #20](https://github.com/iqb-berlin/verona-player-dan/issues/20) via [**ZenHub**](https://www.zenhub.com/)
