### ISSUE TITLE
Eigenschaften Canvas Elemente

### ISSUE THREAD

**Issue by tobhu1981** [iqb-berlin/teststudio-lite-frontend#27]
In den Eigenschaften einiger Canvas Elemente sind die rechten Enden der Auswahlboxen (z.B. Textbox -> Eigenschaften-> Breite) außerhalb des Fensters, sprich die Pfeiltasten (rauf/runter) sind nicht im Bild.

**Comment by mechtelm** [comment]
Wegen der Neufassung in Version 2 (Studio-Lite) nicht mehr relevant.
