### ISSUE TITLE
Spaltensortierung in der Editoren- und Playerliste tut nichts

### ISSUE THREAD

**Issue by rhenck** [iqb-berlin/teststudio-lite-frontend#29]
1. Admin-Ansicht öffnen
 2. Reiter wechseln: "Editoren/Player"
 3. Sicherstellen, dass eine der Listen ein paar Einträge hat
 4. Spaltenkopf der Liste anklicken

Erwartet: Die Tabelle sortiert sich nach der angeklickten Spalte.

Tatsächlich: Die Spalte bekommt den Sortiermarker, aber nichts weiter passiert.

Getested auf:
https://www.iqb-teststudio.de
OS: Ubuntu Linux
Browser: Firefox 98

**Comment by mechtelm** [comment]
Wegen der Neufassung in Version 2 (Studio-Lite) nicht mehr relevant.
